language: go
go:
- master
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get .
script:
- go test -v -covermode=count -coverprofile=coverage.out
- echo $COVERALLS_TOKEN
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
    secure: 8gYBdYRjMW6WTQIdX/2Qyz04/uchAcHb96ygGl+OhqHREjh/Q5hzt4XnjlVOm9Vk7n/sZK1+EtWgEq2C3MKG8OMVHpMeWt5Fu8bp+QZa8GePaYkGvj67ob2i4JhF0eLPqjEpszmQYcln6jkwgGKxkwpTekN6vHGoTvRgNjibBh2mUGcsfxq8+/cm48SPma8fgVtVUlvvSyO0AsLL8lEItGjZwAXgRUNghIjbUeAiPoMa2B/FAe1Vpq7tgaRWw7hzjoB+SZOYT12xASUMT0zyODlKlRb8vff8BqIjIv2oFiWo8kf2Aqflwp4XhGZDE8fa/XkVh1m0/dt7cQSSRil723FupEPlpFJ3CWIm4uB9sxg64W9KwmNSRjyD5NOgTOchy7TfnY6/HFS4VdlnKCLVqpCa0R+eiTDkmn5fKFfj5qRqYYefMefLY80XS7zzXBKrU3sHnDYI7EqODwMCeyGSLLuOQWGc6vLBlvB5HkS92XP6zkTgo2dhCfFQD2Z4YJQUavCu+e5jVGUJUpu1azyd4IHT+RIUhY6tOaTxDKwEpMqHSlCC7LzqVk591wlEWJpdRQd1uPCt4urRLOOQzYjkJQq7hRWqj9bYuWUefptqKyQeSR2tPPOf8NDAnFb4crRSNPSFaovl3nmbMNJqbj623cX02B+2or+nzWj6TJIM1Wc=
